### ISSUE TITLE
Fails with AttributeError when using urllib3 2.x

### ISSUE THREAD

**Issue by schwizzlers** [cebtenzzre/tumblr-utils#15]
Hello,
I've been using the original Python 2.7 version of tumblr-utils to back up my blog, but wanted to try your fork to see if an issue I'm having got fixed. I downloaded Python 3.12 and the `563d6f18c7953468c6b8afbd9c16a0dfab6547ea` version of this repo (most recent version today), and added my OAuth key in the correct place in tumblr_backup.py.

I cannot seem to get a backup to work. I'm running the command `python3 tumblr_backup.py -D --save-video --save-audio -p 2024 blogname` The backup starts, shows a very long `AttributeError` for each post it attempts, and then stops. Here's one example of the error:
```
Caught exception while saving post 738520300008964096:                          
Traceback (most recent call last):                                              
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1969, in save_post
    f.write(self.get_post())                                                    
            ^^^^^^^^^^^^^^^                                                     
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1847, in get_post
    content = self.get_content()                                                
              ^^^^^^^^^^^^^^^^^^                                                
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1530, in get_content
    append_try('body')                                                          
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1514, in append_try
    elt = re.sub(r'''(?i)(<img\s(?:[^>]*\s)?src\s*=\s*["'])(.*?)(["'][^>]*>)''',
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/re/__init__.py", line 186, in sub
    return _compile(pattern, flags).sub(repl, string, count)                    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                    
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1699, in get_inline_image
    saved_name = self.download_media(image_url, filename=image_filename)        
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1791, in download_media
    return self._download_media_inner(url, get_path, path_parts, media_path)    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    
  File "/Users/[redacted]/Downloads/tumblr-utils-master/tumblr_backup.py", line 1817, in _download_media_inner
    wget_retrieve(url, dstpath, post_id=self.ident, post_timestamp=self.post['timestamp'])
  File "/Users/[redacted]/Downloads/tumblr-utils-master/wget.py", line 796, in __call__
    _retrieve_loop(hstat, url, file, post_id, post_timestamp, adjust_basename, self.options, self.log)
  File "/Users/[redacted]/Downloads/tumblr-utils-master/wget.py", line 636, in _retrieve_loop
    err, doctype = gethttp(url, hstat, doctype, logger, retry_counter, options) 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "/Users/[redacted]/Downloads/tumblr-utils-master/wget.py", line 254, in gethttp
    err, doctype = process_response(url, hstat, doctype, logger, retry_counter, resp)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/[redacted]/Downloads/tumblr-utils-master/wget.py", line 268, in process_response
    contlen = resp.get_content_length('GET')                                    
              ^^^^^^^^^^^^^^^^^^^^^^^                                           
AttributeError: 'HTTPResponse' object has no attribute 'get_content_length'. Did you mean: 'enforce_content_length'?
```
I can view the options just fine when running `python3 tumblr_backup.py -h`.
Additionally, every time I run tumblr_backup.py I get this warning message: `warning: filetype module not found, using deprecated imghdr`
Did I miss a step somewhere? I tried symlinking tumblr_backup.py to usr/local/bin as well but got the same errors.  I'm on macOS Mojave, if that helps.

**Comment by 56k-modem** [comment]
Hello, I am also getting this error.

```
$ python3 --version
Python 3.9.2

$ pip list
Package            Version
------------------ ---------------------
annotated-types    0.6.0
attrs              23.1.0
black              23.9.1
boilerpy3          1.0.6
Brotli             1.0.9
cached-property    1.5.2
cdxj-indexer       1.4.5
certifi            2020.6.20
chardet            4.0.0
charset-normalizer 2.1.1
click              8.1.7
colorama           0.4.6
coverage           7.3.2
cryptography       3.3.2
defusedxml         0.7.1
dnspython          2.0.0
docker             4.1.0
docker-compose     1.25.0
dockerpty          0.4.1
docopt             0.6.2
exceptiongroup     1.1.2
filelock           3.12.4
frictionless       5.16.0
gpg                1.14.0-unknown
h11                0.14.0
httplib2           0.18.1
humanize           4.8.0
idna               2.10
importlib-metadata 1.6.0
iniconfig          2.0.0
isodate            0.6.1
jeepney            0.8.0
Jinja2             3.1.2
jsonlines          4.0.0
jsonschema         3.2.0
lxml               4.9.1
Markdown           3.3.4
markdown-it-py     3.0.0
marko              2.0.0
MarkupSafe         2.1.3
mdurl              0.1.2
more-itertools     4.2.0
mutagen            1.46.0
mypy-extensions    1.0.0
outcome            1.2.0
packaging          23.2
pathspec           0.11.2
petl               1.7.14
pip                20.3.4
platformdirs       3.11.0
pluggy             1.3.0
prettytable        3.7.0
Py3AMF             0.8.11
pycountry          22.3.5
pycryptodome       3.16.0
pycryptodomex      3.16.0
pycurl             7.43.0.6
pydantic           2.4.2
pydantic-core      2.10.1
Pygments           2.16.1
pyrsistent         0.15.5
PySimpleSOAP       1.16.2
PySocks            1.7.1
pytest             7.4.2
pytest-cov         4.1.0
python-apt         2.2.1
python-dateutil    2.8.2
python-debian      0.1.39
python-debianbts   3.1.0
python-slugify     8.0.1
PyYAML             5.3.1
reportbug          7.10.3+deb11u1
requests           2.31.0
requests-file      1.5.1
requests-toolbelt  0.9.1
rfc3986            2.0.0
rich               13.6.0
SecretStorage      3.3.3
setuptools         52.0.0
shellingham        1.5.3
shortuuid          1.0.11
simpleeval         0.9.13
six                1.16.0
sniffio            1.3.0
sortedcontainers   2.4.0
streamlink         6.5.0+16.g27087e0b
stringcase         1.2.0
surt               0.3.1
tabulate           0.9.0
text-unidecode     1.3
texttable          1.6.3
tldextract         3.6.0
tomli              2.0.1
totalsize          0.7.2
trio               0.22.2
trio-websocket     0.10.3
typer              0.9.0
typing-extensions  4.7.1
urllib3            2.1.0
validators         0.22.0
wacz               0.4.9
Warcat             2.2.5
warcio             1.7.4
wcwidth            0.2.6
websocket-client   1.4.2
websockets         12.0
wheel              0.34.2
wsproto            1.2.0
yt-dlp             2023.12.6.232721.dev0
zipp               1.0.0

[...]
Traceback (most recent call last):
  File "/usr/local/bin/tumblr_backup", line 1969, in save_post
    f.write(self.get_post())
  File "/usr/local/bin/tumblr_backup", line 1847, in get_post
    content = self.get_content()
  File "/usr/local/bin/tumblr_backup", line 1530, in get_content
    append_try('body')
  File "/usr/local/bin/tumblr_backup", line 1514, in append_try
    elt = re.sub(r'''(?i)(<img\s(?:[^>]*\s)?src\s*=\s*["'])(.*?)(["'][^>]*>)''',
  File "/usr/lib/python3.9/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/local/bin/tumblr_backup", line 1699, in get_inline_image
    saved_name = self.download_media(image_url, filename=image_filename)
  File "/usr/local/bin/tumblr_backup", line 1791, in download_media
    return self._download_media_inner(url, get_path, path_parts, media_path)
  File "/usr/local/bin/tumblr_backup", line 1817, in _download_media_inner
    wget_retrieve(url, dstpath, post_id=self.ident, post_timestamp=self.post['timestamp'])
  File "/home/user/tumblr-utils/wget.py", line 796, in __call__
    _retrieve_loop(hstat, url, file, post_id, post_timestamp, adjust_basename, self.options, self.log)
  File "/home/user/tumblr-utils/wget.py", line 636, in _retrieve_loop
    err, doctype = gethttp(url, hstat, doctype, logger, retry_counter, options)
  File "/home/user/tumblr-utils/wget.py", line 254, in gethttp
    err, doctype = process_response(url, hstat, doctype, logger, retry_counter, resp)
  File "/home/user/tumblr-utils/wget.py", line 268, in process_response
    contlen = resp.get_content_length('GET')
AttributeError: 'HTTPResponse' object has no attribute 'get_content_length'
[...]
```

**Comment by cebtenzzre** [comment]
For now the solution is to `pip install urllib3<2`. I should add support for urllib3 2.x sometime soon, though I'd have to do it in a backwards-compatible way because e.g. Arch Linux still ships urllib3 1.x.

**Comment by 56k-modem** [comment]
Had to add a \ in there, but then it fails with 'too many 502 error responses'.
```
$ python3 -m pip install urllib3<2
-bash: 2: No such file or directory

$ python3 -m pip install urllib3\<2
Defaulting to user installation because normal site-packages is not writeable
Collecting urllib3<2
  Downloading urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 5.4 MB/s eta 0:00:00
Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 13.5 MB/s eta 0:00:00
DEPRECATION: gpg 1.14.0-unknown has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a new
er version of gpg or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.co
m/pypa/pip/issues/12063
Installing collected packages: urllib3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.1.0
    Uninstalling urllib3-2.1.0:
      Successfully uninstalled urllib3-2.1.0
Successfully installed urllib3-1.26.18

$ tumblr_backup 56k-modem

[wget] Error retrieving media
  urllib3 reached a retry limit.
  Caused by: MaxRetryError("WGHTTPSConnectionPool(host='64.media.tumblr.com', port=443): Max retries exceeded with url: /dd0b0fb2c3e57639f0caa5eed4970d44/6bfa4a261ca45334-8e/s640x960/5acd9defbf2393826654a34e3e61f5e38b6a10c5.png (Caused by ResponseError('too many 502 error responses'))")
  Post: 726285923073114112
  URL: https://64.media.tumblr.com/dd0b0fb2c3e57639f0caa5eed4970d44/6bfa4a261ca45334-8e/s640x960/5acd9defbf2393826654a34e3e61f5e38b6a10c5.png
[wget] Error retrieving media
  urllib3 reached a retry limit.
  Caused by: MaxRetryError("WGHTTPSConnectionPool(host='64.media.tumblr.com', port=443): Max retries exceeded with url: /b3f0a613b594ca0baa3380945766b9c5/b6a95fb89106ac3b-0f/s640x960/dbfbf1e2625c60dc107ab4095f64db873b714182.jpg (Caused by ResponseError('too many 502 error responses'))")
  Post: 726700777276637184
  URL: https://64.media.tumblr.com/b3f0a613b594ca0baa3380945766b9c5/b6a95fb89106ac3b-0f/s640x960/dbfbf1e2625c60dc107ab4095f64db873b714182.jpg

[...]
```

**Comment by 56k-modem** [comment]
Confirmed working with the latest pip-installable version, thank you.

**Comment by schwizzlers** [comment]
Just tried again using pip, and yes, everything works now. Thank you!
