### ISSUE TITLE
Unable to set API Key

### ISSUE THREAD

**Issue by thuardu** [cebtenzzre/tumblr-utils#18]
commit: 7becc2b (?); downloaded 2024/02/20

tumblr-backup --set-api-key [REDACTED]

error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\[REDACTED]\AppData\Roaming\Python\Python311\Scripts\tumblr-backup.exe\__main__.py", line 7, in <module>
  File "C:\Users\[REDACTED]\AppData\Roaming\Python\Python311\site-packages\tumblr_backup\main.py", line 2118, in main
    with open(config_file, 'r+') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\[REDACTED]\\AppData\\Roaming\\tumblr-backup\\tumblr-backup\\config.json'

Is the config.json supposed to be automatically generated? There is exactly nothing in the directory in question

**Comment by cebtenzzre** [comment]
Fixed in 4a8d90e84bcca62fe5ae13d421d54959b2dce654, released in version 1.0.1.
