### ISSUE TITLE
Failing with FileNotFoundError at installation step 3

### ISSUE THREAD

**Issue by chimaeraUndying** [cebtenzzre/tumblr-utils#19]
The package installs fine but then throws this error when I try to set my API key (the command for which is on the first line):

```
PS C:\WINDOWS\system32> tumblr-backup --set-api-key REDACTED
Traceback (most recent call last):
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\Scripts\tumblr-backup.exe\__main__.py", line 7, in <module>
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python310\lib\site-packages\tumblr_backup\main.py", line 2118, in main
    with open(config_file, 'r+') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\REDACTED\\AppData\\Roaming\\tumblr-backup\\tumblr-backup\\config.json'
```

This is likely because `with open(config_file, 'r+') as f:` just reads the existing config.json, but nothing's created it yet (or, at least, nothing did in my case).

I was able to fix the issue for myself by creating a config.json in the expected directory with contents `{}` and then re-running the command; everything works fine after that. There's probably a more elegant way to do it, though.

**Comment by cebtenzzre** [comment]
Same as issue #18, fixed in the latest release.
