### ISSUE TITLE
os.fdatasync not supported on macos

### ISSUE THREAD

**Issue by rdlaner** [Cebtenzzre/tumblr-utils#7]
I'm running the latest commit from the `cebtenzzre` branch: 3582d8d

I get the following exception since os.fdatasync is not supported on macos: https://docs.python.org/3/library/os.html#os.fdatasync

```
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "tumblr_backup.py", line 1600, in handler
    work()
  File "tumblr_backup.py", line 1092, in save_content
    append_try('body')
  File "tumblr_backup.py", line 1076, in append_try
    elt = re.sub(r'''(?i)(<img\s(?:[^>]*\s)?src\s*=\s*["'])(.*?)(["'][^>]*>)''',
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "tumblr_backup.py", line 1255, in get_inline_image
    saved_name = self.download_media(image_url, image_filename)
  File "tumblr_backup.py", line 1336, in download_media
    wget_retrieve(url, open_file(lambda f: f, path_parts), post_timestamp=self.post['timestamp'])
  File "/Users/dustinlane/tumblr-utils-fork/tumblr-utils/wget.py", line 736, in __call__
    _retrieve_loop(hstat, url, file, post_timestamp, adjust_basename, self.options, self.log)
  File "/Users/dustinlane/tumblr-utils-fork/tumblr-utils/wget.py", line 690, in _retrieve_loop
    os.fdatasync(hstat.dest_dir)
AttributeError: module 'os' has no attribute 'fdatasync'
```

**Comment by Cebtenzzre** [comment]
Thanks for the report! See if the latest version works for you. I unfortunately don't have a Mac to test the fix on.

**Comment by rdlaner** [comment]
Closer! Now the issue is with `fcntl.F_FULLSYNC`

```
  File "tumblr_backup.py", line 1255, in get_inline_image
    saved_name = self.download_media(image_url, image_filename)
  File "tumblr_backup.py", line 1336, in download_media
    wget_retrieve(url, open_file(lambda f: f, path_parts), post_timestamp=self.post['timestamp'])
  File "/Users/dustinlane/tumblr-utils-fork/tumblr-utils/wget.py", line 736, in __call__
    _retrieve_loop(hstat, url, file, post_timestamp, adjust_basename, self.options, self.log)
  File "/Users/dustinlane/tumblr-utils-fork/tumblr-utils/wget.py", line 670, in _retrieve_loop
    fsync(hstat.part_file)
  File "/Users/dustinlane/tumblr-utils-fork/tumblr-utils/util.py", line 329, in fsync
    fcntl.fcntl(fd, fcntl.F_FULLSYNC)  # pytype: disable=module-attr
AttributeError: module 'fcntl' has no attribute 'F_FULLSYNC'
```

**Comment by Cebtenzzre** [comment]
Typo fixed.
